spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
        namespace: 4a6b5664-8579-4d34-a6a1-cbf2576c22d0
      config:
        # 配置中心地址
        server-addr: 192.168.56.10:8848
        # 配置文件格式
        file-extension: yml
        # 共享配置
        extension-configs:
          - dataId: common-${spring.profiles.active}.yml
            refresh: true
        namespace: 4a6b5664-8579-4d34-a6a1-cbf2576c22d0
    gateway:
      routes:
        #路由 id,没有固定规则，但唯一，建议与服务名对应
        - id: stock
          #匹配后提供服务的路由地址
          uri: lb://mall-stock
          predicates:
            #断言，路径匹配 注意：Path 中 P 为大写
            - Path=/api/stock/**
          filters:
            - RewritePath=/api/stock/?(?<the>.*), /$\{the}
  application:
    name: mall-gateway
  profiles:
    active: dev
  config:
    import: nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  main:
    web-application-type: reactive
server:
  port: 81